### ISSUE TITLE
[FrontEnd] 로그인, 메인 페이지 수정

### ISSUE THREAD

**Issue by eunn43** [boongObbang-plz/boongObbang#21]
## 자세한 기능 설명
* 전체 component 경로 수정 및 img 태그의 alt 속성 추가

## To-do
- [x] 상대경로 -> 절대경로로 수정
- [x] img tag에 alt 속성 추가
- [x] 함수 표현식 화살표 함수로 변경
- [ ] modal 창 크기 수정, transition 적용
