### ISSUE TITLE
[FrontEnd] 남의 메인페이지 구현

### ISSUE THREAD

**Issue by im-madylin** [boongObbang-plz/boongObbang#26]
## 자세한 기능 설명
남의 메인페이지의 도움말, 나의 붕어빵 마차 보기, 붕어빵 굽기(편지쓰기) 구현

## To-do
- [x] 도움말 클릭 시 도움말 팝업
- [x] 나의 붕어빵 마차 보기 클릭 시 로그인 창 이동
- [x] 붕어빵 굽기 클릭 시 편시 쓰기 팝업
