### ISSUE TITLE
[Build] 도커 환경 구축

### ISSUE THREAD

**Issue by dlwndms0812** [boongObbang-plz/boongObbang#3]
## 자세한 기능 설명
DockerFile과 Docker compose로 FrontEnd와 BackEnd를 한번에 빌드하는 도커 환경 구성

## To-do
- [x] FrontEnd DockerFile 작성
- [x] BackEnd DockerFile 작성
- [x] Docker-compose 파일 작성

## 기타
- Docker-compose에서 redis와 mariadb 이미지 가져오기
- BackEnd 파일 내에 mariadb 계정 생성 script 작성
- db 볼륨 생성
