### ISSUE TITLE
[FrontEnd] 반응형으로 수정

### ISSUE THREAD

**Issue by im-madylin** [boongObbang-plz/boongObbang#30]
## 자세한 기능 설명
모바일, 테블릿, pc 크기에 맞춰지도록 반응형으로 수정

## To-do
- [x] 컨텐츠 크기, 위치 조정
- [x] 글꼴 크기 조정
- [x] 최소 크기보다 작아지지 않게 조치
- [x] 최대 크기보다 커질 땐 컨텐츠 고정 후 여백 늘리기
- [x] 최대 크기 이후 모달 크기 고정시키기

## 기타
이미지 비율이 정해져 있어서, 반응형 공부하며 아래 선택지 중 정해질 것 같습니다.
화면 너비에 맞추고, 높이는 스크롤 vs 화면 너비와 높이에 맞추기
