### ISSUE TITLE
[FrontEnd] 남의 메인페이지 & 편지쓰기, 내 메인페이지 편지읽기 & 삭제 API 적용

### ISSUE THREAD

**Issue by im-madylin** [boongObbang-plz/boongObbang#89]
## 자세한 기능 설명
남의 메인페이지 조회와 편지쓰기, 내 메인페이지 편지읽기와 편지삭제 API 적용

## To-do
- [x] 남의 메인페이지 조회 API
- [x] 남의 메인페이지 편지쓰기 API
- [x] 나의 메인페이지 편지읽기 API
- [x] 나의 메인페이지 편지삭제 API
